### ISSUE TITLE
youtube updated, and with it, i think they changed how their ads work

### ISSUE THREAD

**Issue by Buefried** [cdsisthe1/ftube#1]
this might just be a me thing, but this stopped working after youtube updated. just wanted to let you know though

**Comment by cdsisthe1** [comment]
I'll get it fixed out of town currently. I have 2 other YouTube ad skipping extensions fyoutube and fyoutubepy

**Comment by cdsisthe1** [comment]
Hey i fixed everything ive added logging and will start to add more features to be able to update faster.

**Comment by cdsisthe1** [comment]
Hey i fixed everything ive added logging and will start to add more features to be able to update faster.
